"""Add alto_agency_ref to Agency

Revision ID: 71bcc9c08d08
Revises: 
Create Date: 2025-12-09 14:07:26.872288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bcc9c08d08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('alto_agency_ref', sa.String(), nullable=True))
    op.create_index(op.f('ix_agencies_alto_agency_ref'), 'agencies', ['alto_agency_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agencies_alto_agency_ref'), table_name='agencies')
    op.drop_column('agencies', 'alto_agency_ref')
    # ### end Alembic commands ###
